import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import TodoCard from "./TodoCard";
import TextField from "@mui/material/TextField";
import { Box, Button, Typography } from "@mui/material";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [todo, setTodo] = useState("");

  const addTodo = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const res = await fetch("http://localhost:8787/api/todos");
    console.log("res", res);
    console.log("todo", todo);
    setTodo("");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Typography variant="h2" component="h1">
          Todo App
        </Typography>
        <Box
          component={"form"}
          onSubmit={addTodo}
          sx={{ display: "flex", alignItems: "center", gap: 1, minWidth: 500 }}
        >
          <TextField
            id="outlined-basic"
            size="small"
            label="Add todo..."
            variant="outlined"
            value={todo}
            onChange={(e) => setTodo(e.target.value)}
            sx={{ flexGrow: 1 }}
          />
          <Button variant="contained" type="submit">
            Add
          </Button>
        </Box>
        <Box p={2} sx={{ display: "flex", flexDirection: "column", gap: 2 }}>
          <TodoCard id="id1" />
          <TodoCard id="id1" />
        </Box>
      </main>
    </>
  );
}
